Repository saitokazumasa/tabisketch, pull requests merged in 2024-12, with the labels that each got.

#146 svgフラグメントの追加
  src/main/resources/templates/fragment/svg.html
Labels: enhancement, tailwind

#144 メール認証機能を実装
  .run/sql/CreateMailAuthenticationTokens.sql
  src/main/java/com/tabisketch/bean/entity/MailAuthenticationToken.java
  src/main/java/com/tabisketch/bean/valueobject/Mail.java
  src/main/java/com/tabisketch/bean/valueobject/ServerMailAddress.java
  src/main/java/com/tabisketch/controller/AuthenticateMailController.java
  src/main/java/com/tabisketch/controller/RegisterController.java
  src/main/java/com/tabisketch/mapper/IMailAuthenticationTokensMapper.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/main/java/com/tabisketch/service/IAuthenticateMailService.java
  src/main/java/com/tabisketch/service/IRegisterService.java
  src/main/java/com/tabisketch/service/ISendMailService.java
  src/main/java/com/tabisketch/service/ISendRegisterMailService.java
  src/main/java/com/tabisketch/service/implement/AuthenticateMailService.java
  src/main/java/com/tabisketch/service/implement/RegisterService.java
  src/main/java/com/tabisketch/service/implement/SendMailService.java
  src/main/java/com/tabisketch/service/implement/SendRegisterMailService.java
  src/main/resources/templates/mail/confirm.html
  src/test/java/com/tabisketch/controller/AuthenticateMailControllerTest.java
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
  src/test/java/com/tabisketch/mapper/MailAuthenticationTokensMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/service/AuthenticateMailServiceTest.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
  src/test/java/com/tabisketch/service/SendMailServiceTest.java
Labels: enhancement

#150 テストのエラーハンドリングリファクタ&初期SQLデータ自動作成スクリプト追加
  .run/sql/InsertExampleUser.sql
  src/test/java/com/tabisketch/controller/AuthenticateMailControllerTest.java
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
  src/test/java/com/tabisketch/controller/IndexControllerTest.java
  src/test/java/com/tabisketch/controller/ListPlanControllerTest.java
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
  src/test/java/com/tabisketch/controller/TopControllerTest.java
  src/test/java/com/tabisketch/mapper/MailAuthenticationTokensMapperTest.java
  src/test/java/com/tabisketch/mapper/PlansMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
  src/test/java/com/tabisketch/service/SendMailServiceTest.java
  src/test/resources/sql/CreateMailAuthenticationToken.sql
  src/test/resources/sql/CreateUser.sql
Labels: refactor

#151 余計な行などを削除
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
  src/test/java/com/tabisketch/controller/EditUserControllerTest.java
  src/test/java/com/tabisketch/controller/ListPlanControllerTest.java
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
Labels: refactor

#141 目的地追加時にフラグメント追加
  src/main/resources/static/js/autocomplete.js
  src/main/resources/static/js/modal.js
  src/main/resources/templates/fragment/modal.html
  src/main/resources/templates/fragment/script.html
Labels: enhancement, refactor

#161 現段階でできている所まで結合
  src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/plan/list.html
Labels: enhancement

#165 ESLintエラー箇所の修正
  eslint.config.mjs
  src/main/resources/static/js/autocomplete.js
  src/main/resources/static/js/header.js
  src/main/resources/static/js/modal.js
  src/main/resources/static/js/top.js
Labels: refactor

#156 ESLint の適用
  .github/workflows/eslint.yml
  eslint.config.mjs
  package-lock.json
  package.json
  src/main/resources/static/js/autocomplete.js
  src/main/resources/static/js/header.js
  src/main/resources/static/js/modal.js
  src/main/resources/static/js/top.js
Labels: enhancement

#176 ESlintの設定を編集
  eslint.config.mjs
Labels: fix

#172 メールアドレス編集機能を実装
  .run/sql/CreateMailAuthenticationTokens.sql
  src/main/java/com/tabisketch/bean/entity/MailAuthenticationToken.java
  src/main/java/com/tabisketch/bean/form/IsMatchPasswordForm.java
  src/main/java/com/tabisketch/bean/form/RegisterForm.java
  src/main/java/com/tabisketch/bean/form/SendEditMailForm.java
  src/main/java/com/tabisketch/bean/valueobject/EncryptedPassword.java
  src/main/java/com/tabisketch/bean/valueobject/Mail.java
  src/main/java/com/tabisketch/controller/SendEditMailController.java
  src/main/java/com/tabisketch/mapper/IMailAuthenticationTokensMapper.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/main/java/com/tabisketch/service/IIsExistMailService.java
  src/main/java/com/tabisketch/service/IIsMatchPasswordService.java
  src/main/java/com/tabisketch/service/ISendEditMailService.java
  src/main/java/com/tabisketch/service/implement/AuthenticateMailService.java
  src/main/java/com/tabisketch/service/implement/IsExistMailService.java
  src/main/java/com/tabisketch/service/implement/IsMatchPasswordService.java
  src/main/java/com/tabisketch/service/implement/SendEditMailService.java
  src/main/resources/templates/user/edit/mail/index.html
  src/main/resources/templates/user/edit/mail/send.html
  src/test/java/com/tabisketch/controller/SendEditMailControllerTest.java
  src/test/java/com/tabisketch/mapper/MailAuthenticationTokensMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/service/IsExistMailServiceTest.java
  src/test/java/com/tabisketch/service/IsMatchPasswordServiceTest.java
  src/test/java/com/tabisketch/service/SendEditMailServiceTest.java
Labels: enhancement

#181 controllerでの@AuthenticationPrincipalでユーサ名を取得する方法をリファクタ
  src/main/java/com/tabisketch/controller/ListPlanController.java
Labels: refactor

#182 Entityクラスの変数をprivateに変更
  src/main/java/com/tabisketch/bean/entity/Plan.java
  src/main/java/com/tabisketch/bean/entity/User.java
Labels: refactor

#174 ModalFormの入力内容をSessionに保存
  src/main/resources/static/js/autocomplete.js
  src/main/resources/static/js/modal.js
  src/main/resources/templates/fragment/modal.html
Labels: enhancement

#187 TopページのThymeleafの呼び出しの修正
  src/main/resources/templates/top.html
Labels: fix

#167 経路作成画面のデザインとスクリプト作成
  src/main/resources/static/js/checkSession.js
  src/main/resources/static/js/map.js
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/plan/create.html
Labels: enhancement, tailwind

#188 テストをリファクタ
  .run/CreateTables.run.xml
  .run/DropTables.run.xml
  .run/sql/CreateMailAuthTokens.sql
  .run/sql/CreateMailAuthenticationTokens.sql
  .run/sql/CreateUsersTable.sql
  .run/sql/DropMaiAddressAuthTokensTable.sql
  .run/sql/DropMailAuthenticationsTable.sql
  src/main/java/com/tabisketch/bean/entity/MailAddressAuthToken.java
  src/main/java/com/tabisketch/bean/entity/User.java
  src/main/java/com/tabisketch/bean/form/IsMatchPasswordForm.java
  src/main/java/com/tabisketch/bean/form/RegisterForm.java
  src/main/java/com/tabisketch/bean/form/SendEditMailForm.java
  src/main/java/com/tabisketch/bean/valueobject/EncryptedPassword.java
  src/main/java/com/tabisketch/controller/AuthMailAddressController.java
  src/main/java/com/tabisketch/controller/EditUserController.java
  src/main/java/com/tabisketch/controller/ListPlanController.java
  src/main/java/com/tabisketch/controller/RegisterController.java
  src/main/java/com/tabisketch/controller/SendEditMailController.java
  src/main/java/com/tabisketch/mapper/IMailAddressAuthTokensMapper.java
  src/main/java/com/tabisketch/mapper/IMailAuthenticationTokensMapper.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/main/java/com/tabisketch/security/LoginUserDetails.java
  src/main/java/com/tabisketch/security/LoginUserDetailsService.java
  src/main/java/com/tabisketch/service/IAuthMailAddressService.java
  src/main/java/com/tabisketch/service/IEncryptPasswordService.java
  src/main/java/com/tabisketch/service/ISendMailService.java
  src/main/java/com/tabisketch/service/implement/AuthMailAddressService.java
  src/main/java/com/tabisketch/service/implement/AuthenticateMailService.java
  src/main/java/com/tabisketch/service/implement/EncryptPasswordService.java
  src/main/java/com/tabisketch/service/implement/IsExistMailService.java
  src/main/java/com/tabisketch/service/implement/IsMatchPasswordService.java
  src/main/java/com/tabisketch/service/implement/ListPlanService.java
  src/main/java/com/tabisketch/service/implement/RegisterService.java
  src/main/java/com/tabisketch/service/implement/SendEditMailService.java
  src/main/java/com/tabisketch/service/implement/SendMailService.java
  src/main/java/com/tabisketch/valueobject/Mail.java
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/register/index.html
  src/main/resources/templates/user/edit/index.html
  src/main/resources/templates/user/edit/mail/index.html
  src/test/java/com/tabisketch/controller/AuthMailAddressControllerTest.java
  src/test/java/com/tabisketch/controller/EditUserControllerTest.java
  src/test/java/com/tabisketch/controller/ListPlanControllerTest.java
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
  src/test/java/com/tabisketch/controller/SendEditMailControllerTest.java
  src/test/java/com/tabisketch/mapper/MailAddressAuthTokensMapperTest.java
  src/test/java/com/tabisketch/mapper/MailAuthenticationTokensMapperTest.java
  src/test/java/com/tabisketch/mapper/PlansMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/service/AuthMailAddressServiceTest.java
  src/test/java/com/tabisketch/service/AuthenticateMailServiceTest.java
  src/test/java/com/tabisketch/service/EncryptPasswordServiceTest.java
  src/test/java/com/tabisketch/service/IsExistMailServiceTest.java
  src/test/java/com/tabisketch/service/IsMatchPasswordServiceTest.java
  src/test/java/com/tabisketch/service/ListPlanServiceTest.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
  src/test/java/com/tabisketch/service/SendEditMailServiceTest.java
  src/test/java/com/tabisketch/service/SendMailServiceTest.java
  src/test/resources/sql/CreateMailAuthenticationToken.sql
  src/test/resources/sql/CreateUser.sql
Labels: refactor

#197 mailをmailAddressと区別した際の修正漏れを修正
  .run/CreateTables.run.xml
  .run/sql/CreateMailAddressAuthTokensTable.sql
  .run/sql/CreateUsersTable.sql
  src/main/java/com/tabisketch/bean/entity/User.java
  src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
  src/main/java/com/tabisketch/controller/RegisterController.java
  src/main/java/com/tabisketch/controller/SendEditMailController.java
  src/main/java/com/tabisketch/mapper/IMailAddressAuthTokensMapper.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/main/java/com/tabisketch/security/LoginUserDetailsService.java
  src/main/java/com/tabisketch/service/IIsExistMailAddressService.java
  src/main/java/com/tabisketch/service/IIsExistMailService.java
  src/main/java/com/tabisketch/service/IListPlanService.java
  src/main/java/com/tabisketch/service/implement/AuthMailAddressService.java
  src/main/java/com/tabisketch/service/implement/IsExistMailAddressService.java
  src/main/java/com/tabisketch/service/implement/IsExistMailService.java
  src/main/java/com/tabisketch/service/implement/RegisterService.java
  src/main/java/com/tabisketch/service/implement/SendEditMailService.java
  src/main/java/com/tabisketch/service/implement/SendMailService.java
  src/main/java/com/tabisketch/valueobject/Mail.java
  src/main/resources/templates/login.html
  src/main/resources/templates/register/send.html
  src/main/resources/templates/user/edit/mail/send.html
  src/main/resources/templates/user/register/send.html
  src/test/java/com/tabisketch/controller/AuthMailAddressControllerTest.java
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
  src/test/java/com/tabisketch/controller/SendEditMailControllerTest.java
  src/test/java/com/tabisketch/mapper/MailAddressAuthTokensMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/service/AuthMailAddressServiceTest.java
  src/test/java/com/tabisketch/service/IsExistMailAddressServiceTest.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
  src/test/java/com/tabisketch/service/SendEditMailServiceTest.java
  src/test/java/com/tabisketch/service/SendMailServiceTest.java
  src/test/resources/sql/CreateMailAddressAuthToken.sql
Labels: bug, refactor

#191 map.jsの動作に不備があったため修正
  src/main/resources/static/js/map.js
  src/main/resources/templates/fragment/script.html
Labels: fix

#194 場所の表示をform内容に変更・sessionに値がある時に初期表示作成
  src/main/resources/static/js/modal.js
  src/main/resources/templates/fragment/modal.html
  src/main/resources/templates/fragment/svg.html
Labels: enhancement, tailwind, refactor

#199 旅行プラン詳細ページのデザイン作成
  src/main/resources/templates/share/plan.html
Labels: enhancement, tailwind

#205 旅行プラン作成に必要な各種Mapperを実装
  .run/sql/CreateDaysTable.sql
  .run/sql/CreatePlacesTable.sql
  src/main/java/com/tabisketch/bean/entity/Day.java
  src/main/java/com/tabisketch/bean/entity/Place.java
  src/main/java/com/tabisketch/bean/entity/Plan.java
  src/main/java/com/tabisketch/constant/Transportation.java
  src/main/java/com/tabisketch/mapper/IDaysMapper.java
  src/main/java/com/tabisketch/mapper/IPlacesMapper.java
  src/main/java/com/tabisketch/mapper/IPlansMapper.java
  src/test/java/com/tabisketch/mapper/DaysMapperTest.java
  src/test/java/com/tabisketch/mapper/PlacesMapperTest.java
  src/test/java/com/tabisketch/mapper/PlansMapperTest.java
  src/test/resources/sql/CreateDay.sql
  src/test/resources/sql/CreateGooglePlace.sql
  src/test/resources/sql/CreatePlace.sql
  src/test/resources/sql/CreatePlan.sql
Labels: enhancement

#208 旅行プラン削除・更新機能を作成
  src/main/java/com/tabisketch/controller/DeletePlanController.java
  src/main/java/com/tabisketch/controller/EditPlanController.java
  src/main/java/com/tabisketch/mapper/IDaysMapper.java
  src/main/java/com/tabisketch/mapper/IPlacesMapper.java
  src/main/java/com/tabisketch/mapper/IPlansMapper.java
  src/main/java/com/tabisketch/service/IDeletePlanService.java
  src/main/java/com/tabisketch/service/implement/DeletePlanService.java
  src/main/resources/templates/plan/edit.html
  src/test/java/com/tabisketch/controller/DeletePlanControllerTest.java
  src/test/java/com/tabisketch/controller/EditPlanControllerTest.java
  src/test/java/com/tabisketch/mapper/DaysMapperTest.java
  src/test/java/com/tabisketch/mapper/PlacesMapperTest.java
  src/test/java/com/tabisketch/mapper/PlansMapperTest.java
  src/test/java/com/tabisketch/service/DeletePlanServiceTest.java
  src/test/resources/sql/CreatePlace.sql
  src/test/resources/sql/CreatePlan.sql
Labels: enhancement

#218 詳細画面の場所表示
  src/main/resources/templates/fragment/detail-place.html
  src/main/resources/templates/fragment/svg.html
  src/main/resources/templates/share/plan.html
Labels: enhancement, tailwind

#215 経路編集画面のデザイン作成
  src/main/resources/static/css/input.css
  src/main/resources/static/js/check.js
  src/main/resources/static/js/checkSession.js
  src/main/resources/static/js/redirect.js
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/plan/edit.html
Labels: enhancement, tailwind, WIP

#229 @MockBeanが非推奨になったため@MockitoBeanに更新
  src/test/java/com/tabisketch/controller/AuthMailAddressControllerTest.java
  src/test/java/com/tabisketch/controller/DeletePlanControllerTest.java
  src/test/java/com/tabisketch/controller/EditMailAddressControllerTest.java
  src/test/java/com/tabisketch/controller/ListPlanControllerTest.java
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
  src/test/java/com/tabisketch/service/AuthMailAddressServiceTest.java
  src/test/java/com/tabisketch/service/DeletePlanServiceTest.java
  src/test/java/com/tabisketch/service/EditMailAddressServiceTest.java
  src/test/java/com/tabisketch/service/ListPlanServiceTest.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
  src/test/java/com/tabisketch/service/SendMailServiceTest.java
Labels: enhancement, refactor

#233 googleMapsAPIの呼び出し方修正
  src/main/resources/templates/fragment/script.html
Labels: fix

#236 ログイン後、エラーページに飛んでしまうバグを修正
  src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
  src/main/java/com/tabisketch/controller/LoginController.java
Labels: bug, java

#241 booleanにisを使わないことにした
  .run/sql/CreateDaysTable.sql
  .run/sql/CreatePlansTable.sql
  .run/sql/CreateUsersTable.sql
  src/main/java/com/tabisketch/bean/entity/Day.java
  src/main/java/com/tabisketch/bean/entity/Plan.java
  src/main/java/com/tabisketch/bean/entity/User.java
  src/main/java/com/tabisketch/bean/form/RegisterForm.java
  src/main/java/com/tabisketch/service/implement/AuthMailAddressService.java
  src/main/java/com/tabisketch/service/implement/EditMailAddressService.java
  src/main/java/com/tabisketch/util/StringUtils.java
Labels: refactor, java

#237 Plan作成APIを作成
  src/main/java/com/tabisketch/bean/form/CreatePlanForm.java
  src/main/java/com/tabisketch/bean/response/CreatePlanResponse.java
  src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
  src/main/java/com/tabisketch/controller/CreatePlanAPIController.java
  src/main/java/com/tabisketch/controller/CreatePlanController.java
  src/main/java/com/tabisketch/service/ICreatePlanService.java
  src/main/java/com/tabisketch/service/implement/CreatePlanService.java
  src/main/java/com/tabisketch/valueobject/Mail.java
  src/test/java/com/tabisketch/controller/CreatePlanAPIControllerTest.java
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
  src/test/java/com/tabisketch/service/CreatePlanServiceTest.java
Labels: enhancement, java

#238 Day作成APIを作成
  src/main/java/com/tabisketch/bean/form/CreateDayForm.java
  src/main/java/com/tabisketch/bean/response/CreateDayResponse.java
  src/main/java/com/tabisketch/bean/response/IResponse.java
  src/main/java/com/tabisketch/controller/CreateDayAPIController.java
  src/main/java/com/tabisketch/service/ICreateDayService.java
  src/main/java/com/tabisketch/service/implement/CreateDayService.java
  src/test/java/com/tabisketch/controller/CreateDayAPIControllerTest.java
  src/test/java/com/tabisketch/service/CreateDayServiceTest.java
Labels: enhancement, java

#239 Place作成APIを作成
  src/main/java/com/tabisketch/bean/form/CreatePlaceForm.java
  src/main/java/com/tabisketch/bean/response/CreatePlaceResponse.java
  src/main/java/com/tabisketch/controller/CreatePlaceAPIController.java
  src/main/java/com/tabisketch/service/ICreatePlaceService.java
  src/main/java/com/tabisketch/service/implement/CreatePlaceService.java
  src/test/java/com/tabisketch/controller/CreatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/service/CreatePlaceServiceTest.java
Labels: enhancement, java

#228 経路作成画面の修正と更新
  src/main/resources/templates/plan/create.html
Labels: fix

#232 ModalのForm部分修正
  src/main/resources/static/js/modal.js
  src/main/resources/templates/fragment/modal.html
Labels: fix

#185 ポップアップ画面を作成
  src/main/resources/static/js/linkShareButton.js
  src/main/resources/static/js/previewImage.js
  src/main/resources/static/js/shareToggleButton.js
  src/main/resources/templates/fragment/popup.html
  src/main/resources/templates/fragment/script.html
Labels: tailwind

#206 おすすめ目的地の表示作成
  src/main/resources/static/js/modal.js
  src/main/resources/static/js/recommend.js
  src/main/resources/templates/fragment/recommend.html
  src/main/resources/templates/fragment/script.html
Labels: enhancement, tailwind

#248 経路編集画面の作成
  package-lock.json
  package.json
  src/main/resources/static/js/draganddrop.js
  src/main/resources/static/js/radioButtonSelect.js
  src/main/resources/templates/fragment/head.html
  src/main/resources/templates/fragment/svg.html
  src/main/resources/templates/plan/edit.html
Labels: tailwind
