Repository saitokazumasa/tabisketch, pull requests merged in 2024-11, with the labels that each got.

#7 tailwind css を導入
  .gitignore
  package-lock.json
  package.json
  src/main/resources/static/css/input.css
  src/main/resources/static/css/tailwind.css
  tailwind.config.js
Labels: enhancement

#8 READMEを更新
  README.md
Labels: documentation

#9 README に Tailwind CSS について記載
  README.md
Labels: documentation

#10 issue template を追加
  .github/ISSUE_TEMPLATE/feature_request_temp.md
Labels: documentation

#11 tailwind.config の設定
  src/main/resources/static/css/input.css
  src/main/resources/static/css/tailwind.css
  tailwind.config.js
Labels: enhancement

#15 tailwind button components の作成
  src/main/resources/static/css/input.css
  src/main/resources/static/css/tailwind.css
  tailwind.config.js
Labels: enhancement, tailwind

#22 tailwind input components の作成
  src/main/resources/static/css/input.css
  src/main/resources/static/css/tailwind.css
  tailwind.config.js
Labels: enhancement, tailwind

#23 headをlayout化させた
  src/main/resources/templates/fragment/head.html
Labels: enhancement

#29 gitignore に tailwind.cssを追加
  .gitignore
Labels: tailwind

#32 pull request template を追加
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#35 SpringSecurityとlombokの追加
  pom.xml
Labels: enhancement

#34 レスポンシブデザインを適用するための設定追加
  src/main/resources/templates/fragment/head.html
Labels: enhancement, tailwind

#39 フォントカラーやフォントサイズの追加
  tailwind.config.js
Labels: tailwind

#41 セキュリティ設定を実装
  README.md
  pom.xml
  src/main/java/com/tabisketch/bean/User.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/main/java/com/tabisketch/security/LoginUserDetails.java
  src/main/java/com/tabisketch/security/LoginUserDetailsService.java
  src/main/java/com/tabisketch/security/WebSecurityConfiguration.java
  src/main/resources/application.properties
  src/test/java/com/tabisketch/security/LoginUserDetailsServiceTest.java
Labels: enhancement

#52 IndexControllerの作成
  src/main/java/com/tabisketch/controller/IndexController.java
Labels: enhancement

#54 logincontrollerの作成
  src/main/java/com/tabisketch/controller/LoginController.java
Labels: enhancement

#57 Tailwind config の修正
  tailwind.config.js
Labels: tailwind

#36 layoutのheaderを作成
  package-lock.json
  package.json
  pom.xml
  src/main/resources/static/css/tailwind.css
  src/main/resources/static/js/header.js
  src/main/resources/templates/fragment/header.html
  src/main/resources/templates/fragment/script.html
  tailwind.config.js
Labels: enhancement, tailwind

#51 ログインページのデザイン作成
  src/main/resources/templates/login.html
Labels: enhancement, tailwind

#40 footerのレイアウトを作成
  src/main/resources/templates/fragment/footer.html
Labels: enhancement, tailwind

#53 アカウント新規作成ページのデザイン作成
  src/main/resources/templates/User/create.html
Labels: enhancement, tailwind

#65 既存ページのfooterを適用するための設定を追加する
  src/main/resources/templates/User/create.html
  src/main/resources/templates/login.html
Labels: fix

#69 プルリクテンプレ close の後が全角スペースになっているのを修正
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, refactor

#66 headにデフォルトのフォントカラーを適用
  src/main/resources/static/css/common.css
  src/main/resources/templates/User/create.html
  src/main/resources/templates/fragment/head.html
  src/main/resources/templates/login.html
  tailwind.config.js
Labels: fix

#71 パスワードリセット(メール確認)ページの作成
  src/main/resources/templates/user/create.html
  src/main/resources/templates/user/password-reset-sender.html
Labels: enhancement, tailwind

#79 最新のレイアウトの呼び出し方に修正
  src/main/resources/templates/login.html
  src/main/resources/templates/user/create.html
Labels: fix

#81 IndexController が機能していないバグを修正
  src/main/java/com/tabisketch/controller/IndexController.java
  src/main/java/com/tabisketch/controller/TopController.java
  src/main/resources/templates/top.html
  src/test/java/com/tabisketch/controller/IndexControllerTest.java
  src/test/java/com/tabisketch/controller/TopControllerTest.java
Labels: bug, refactor

#77 パスワードリセット画面の作成
  src/main/resources/templates/user/password-reset.html
Labels: enhancement, tailwind

#78 tailwind svgのコンポーネント作成
  src/main/resources/static/css/input.css
  src/main/resources/templates/fragment/svg.html
Labels: tailwind

#72 headerの修正
  src/main/resources/static/images/icon.png
  src/main/resources/static/js/header.js
  src/main/resources/templates/fragment/header.html
Labels: tailwind, fix

#87 WebSecurityConfig に static コンテンツのパスを追加
  src/main/java/com/tabisketch/security/WebSecurityConfiguration.java
Labels: refactor

#86 Entity Package を作成
  src/main/java/com/tabisketch/bean/entity/Plan.java
  src/main/java/com/tabisketch/bean/entity/User.java
  src/main/java/com/tabisketch/mapper/IPlansMapper.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/main/java/com/tabisketch/security/LoginUserDetails.java
  src/main/java/com/tabisketch/security/LoginUserDetailsService.java
  src/test/java/com/tabisketch/mapper/PlansMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/security/LoginUserDetailsServiceTest.java
Labels: refactor

#85 ユーザー新規登録のルーティングを作成
  pom.xml
  src/main/java/com/tabisketch/bean/form/CreateUserForm.java
  src/main/java/com/tabisketch/controller/CreateUserController.java
  src/main/java/com/tabisketch/security/WebSecurityConfiguration.java
  src/main/resources/templates/user/create-confirm.html
  src/main/resources/templates/user/create.html
  src/test/java/com/tabisketch/controller/CreateUserControllerTest.java
Labels: enhancement

#92 WebSecurityConfigrationの静的ファイル認可の修正
  src/main/java/com/tabisketch/security/WebSecurityConfiguration.java
Labels: fix

#95 パスワード編集画面の作成
  src/main/resources/templates/user/edit/password.html
Labels: enhancement, tailwind

#99 アカウント編集のメニュー画面作成
  src/main/resources/templates/user/edit/index.html
Labels: enhancement, tailwind

#90 メールアドレス編集画面の作成
  src/main/resources/templates/user/edit/mail.html
Labels: enhancement, tailwind

#104 テストに使用するサンプルメールアドレスを変更など
  src/test/java/com/tabisketch/mapper/PlansMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/security/LoginUserDetailsServiceTest.java
Labels: refactor

#100 TOPページの作成
  src/main/resources/static/images/top1.png
  src/main/resources/static/images/top2.png
  src/main/resources/static/images/top3.png
  src/main/resources/static/images/top4.png
  src/main/resources/static/images/top5.png
  src/main/resources/static/images/top6.png
  src/main/resources/static/js/top.js
  src/main/resources/templates/top.html
Labels: enhancement, tailwind

#101 SQLコマンドのドキュメントを作成
  .github/SQL.md
Labels: documentation

#112 Tailwind.css を ignore & 実行時に tailwind のビルドを自動実行できるようにした
  .gitignore
  .run/BuildAndRun.run.xml
  .run/TailwindCSSBuild.run.xml
  README.md
  src/main/resources/static/css/tailwind.css
Labels: refactor

#110 Modalフラグメント作成
  package-lock.json
  package.json
  src/main/resources/static/js/flowbite.min.js
  src/main/resources/templates/fragment/modal.html
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/fragment/svg.html
  tailwind.config.js
Labels: enhancement, tailwind

#114 Google Map API キーの設定
  README.md
  src/main/resources/application.properties
Labels: enhancement

#103 各確認画面のデザイン作成
  src/main/resources/templates/user/create-confirm.html
  src/main/resources/templates/user/edit/send/send.html
  src/main/resources/templates/user/password-reset/send.html
  src/main/resources/templates/user/register/send.html
Labels: enhancement, tailwind

#116 PlanListControllerの作成
  src/main/java/com/tabisketch/controller/ListPlanController.java
  src/main/resources/templates/plan/list.html
  src/test/java/com/tabisketch/controller/PlanListControllerTest.java
Labels: enhancement

#117 IUsersMapper に Insert を追加
  src/main/java/com/tabisketch/bean/entity/User.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
Labels: enhancement

#120 Modal に場所検索の API適用
  src/main/resources/static/js/autocomplete.js
  src/main/resources/static/js/modal.js
  src/main/resources/templates/fragment/modal.html
  src/main/resources/templates/fragment/script.html
Labels: enhancement

#119 SQL テーブル自動作成.run を作成
  .github/SQL.md
  .run/CreateTables.run.xml
  .run/DropTables.run.xml
  .run/sql/CreateDaysTable.sql
  .run/sql/CreateGooglePlaceTypesTable.sql
  .run/sql/CreateGooglePlacesTable.sql
  .run/sql/CreateGoogleTypeAssociationsTable.sql
  .run/sql/CreateMailAuthenticationTokens.sql
  .run/sql/CreatePackingsTable.sql
  .run/sql/CreatePasswordResetTokensTable.sql
  .run/sql/CreatePlacesTable.sql
  .run/sql/CreatePlansTable.sql
  .run/sql/CreateTransportationsType.sql
  .run/sql/CreateUsersTable.sql
  .run/sql/DropDaysTable.sql
  .run/sql/DropGooglePlaceTypesTable.sql
  .run/sql/DropGooglePlacesTable.sql
  .run/sql/DropGoogleTypeAssociationsTable.sql
  .run/sql/DropMailAuthenticationsTable.sql
  .run/sql/DropPackingsTable.sql
  .run/sql/DropPasswordResetTokensTable.sql
  .run/sql/DropPlacesTable.sql
  .run/sql/DropPlansTable.sql
  .run/sql/DropTransportationsTable.sql
  .run/sql/DropUsersTable.sql
  .run/sql/InsertExampleUser.sql
  README.md
Labels: refactor

#123 プラン作成ページのコントローラーを作成
  src/main/java/com/tabisketch/controller/CreatePlanController.java
  src/main/resources/templates/plan/create.html
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
Labels: enhancement

#127 ファイル名の変更
  src/test/java/com/tabisketch/controller/ListPlanControllerTest.java
Labels: refactor

#128 旅行プラン一覧画面の作成
  src/main/resources/templates/plan/list.html
Labels: enhancement, tailwind

#130 ユーザー新規登録Serviceを作成
  src/main/java/com/tabisketch/bean/form/RegisterForm.java
  src/main/java/com/tabisketch/bean/valueobject/EncryptedPassword.java
  src/main/java/com/tabisketch/controller/RegisterController.java
  src/main/java/com/tabisketch/security/WebSecurityConfiguration.java
  src/main/java/com/tabisketch/service/IRegisterService.java
  src/main/java/com/tabisketch/service/implement/RegisterService.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
Labels: enhancement

#132 登録確認メール送信機能を実装
  README.md
  pom.xml
  src/main/java/com/tabisketch/bean/valueobject/ServerMailAddress.java
  src/main/java/com/tabisketch/configuration/AsyncConfiguration.java
  src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
  src/main/java/com/tabisketch/controller/RegisterController.java
  src/main/java/com/tabisketch/service/ISendRegisterMailService.java
  src/main/java/com/tabisketch/service/implement/SendRegisterMailService.java
  src/main/resources/application.properties
  src/test/java/com/tabisketch/service/SendRegisterMailServiceTest.java
Labels: enhancement

#133 エラーハンドリング部分などをリファクタ
  src/main/java/com/tabisketch/service/IRegisterService.java
  src/main/java/com/tabisketch/service/implement/RegisterService.java
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
  src/test/java/com/tabisketch/controller/IndexControllerTest.java
  src/test/java/com/tabisketch/controller/ListPlanControllerTest.java
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
  src/test/java/com/tabisketch/controller/TopControllerTest.java
  src/test/java/com/tabisketch/mapper/PlansMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
Labels: enhancement

#138 テストデータprovide関数をprivateに変更
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
Labels: refactor
