Repository saitokazumasa/tabisketch, pull requests merged in 2025-01, with the labels that each got.

#245 GithubActionsでJavaをテストするフローを作成
  .github/PULL_REQUEST_TEMPLATE/pull_request_temp.md
  .github/workflows/build_and_run.yml
  .github/workflows/eslint.yml
  .run/CreateTables.run.xml
  .run/DropTables.run.xml
  .run/bin/BuildTailwindCss.sh
  .run/bin/CreateTables.sh
  .run/bin/DropTables.sh
  .run/sql/CreateTables.sql
  .run/sql/DropTables.sql
  .run/sql/create/CreateDaysTable.sql
  .run/sql/create/CreateGooglePlaceTypesTable.sql
  .run/sql/create/CreateGooglePlacesTable.sql
  .run/sql/create/CreateGoogleTypeAssociationsTable.sql
  .run/sql/create/CreateMAATokensTable.sql
  .run/sql/create/CreatePackingsTable.sql
  .run/sql/create/CreatePasswordResetTokensTable.sql
  .run/sql/create/CreatePlacesTable.sql
  .run/sql/create/CreatePlansTable.sql
  .run/sql/create/CreateTransportationsType.sql
  .run/sql/create/CreateUsersTable.sql
  .run/sql/drop/DropDaysTable.sql
  .run/sql/drop/DropGooglePlaceTypesTable.sql
  .run/sql/drop/DropGooglePlacesTable.sql
  .run/sql/drop/DropGoogleTypeAssociationsTable.sql
  .run/sql/drop/DropMAATokensTable.sql
  .run/sql/drop/DropPackingsTable.sql
  .run/sql/drop/DropPasswordResetTokensTable.sql
  .run/sql/drop/DropPlacesTable.sql
  .run/sql/drop/DropPlansTable.sql
  .run/sql/drop/DropTransportationsTable.sql
  .run/sql/drop/DropUsersTable.sql
  README.md
  mvnw
  pom.xml
  src/main/java/com/tabisketch/mapper/IPlansMapper.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/main/resources/templates/plan/create.html
  src/main/resources/templates/plan/edit.html
  src/main/resources/templates/share/plan.html
Labels: enhancement

#240 GooglePlace作成APIを作成
  src/main/java/com/tabisketch/bean/entity/GooglePlace.java
  src/main/java/com/tabisketch/bean/form/CreateGooglePlaceForm.java
  src/main/java/com/tabisketch/bean/response/CreateGooglePlaceResponse.java
  src/main/java/com/tabisketch/controller/CreateGooglePlaceAPIController.java
  src/main/java/com/tabisketch/mapper/IGooglePlaceMapper.java
  src/main/java/com/tabisketch/service/ICreateGooglePlaceService.java
  src/main/java/com/tabisketch/service/implement/CreateGooglePlaceService.java
  src/test/java/com/tabisketch/controller/CreateGooglePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/mapper/GooglePlaceMapperTest.java
  src/test/java/com/tabisketch/service/CreateGooglePlaceServiceTest.java
Labels: enhancement, java

#254 パスワード編集機能を作成
  .github/PULL_REQUEST_TEMPLATE.md
  .run/sql/create/CreateDaysTable.sql
  .run/sql/create/CreatePlansTable.sql
  src/main/java/com/tabisketch/bean/form/EditMailAddressForm.java
  src/main/java/com/tabisketch/bean/form/EditPasswordForm.java
  src/main/java/com/tabisketch/controller/EditMailAddressController.java
  src/main/java/com/tabisketch/controller/EditPasswordController.java
  src/main/java/com/tabisketch/service/IEditPasswordService.java
  src/main/java/com/tabisketch/service/implement/EditMailAddressService.java
  src/main/java/com/tabisketch/service/implement/EditPasswordService.java
  src/main/java/com/tabisketch/valueobject/Mail.java
  src/main/resources/templates/user/edit/mail/index.html
  src/main/resources/templates/user/edit/password/confirm.html
  src/main/resources/templates/user/edit/password/index.html
  src/test/java/com/tabisketch/controller/EditPasswordControllerTest.java
  src/test/java/com/tabisketch/service/EditPasswordServiceTest.java
Labels: enhancement

#260 ログイン失敗したときのエラー表示を追加
  src/main/resources/templates/login.html
Labels: tailwind

#259 メール認証確認表示の作成
  src/main/resources/templates/fragment/mail-confirm.html
  src/main/resources/templates/fragment/script.html
Labels: enhancement

#263 パスワード変更確認通知ページの作成
  src/main/resources/templates/user/edit/password/confirm.html
Labels: enhancement, tailwind

#268 ボタンの属性を変更
  src/main/resources/templates/register/send.html
  src/main/resources/templates/user/edit/mail/send.html
  src/main/resources/templates/user/password-reset/send.html
Labels: fix

#269 各エラー文のコメントアウト削除
  src/main/resources/static/css/input.css
  src/main/resources/templates/password-reset/index.html
  src/main/resources/templates/register/index.html
  src/main/resources/templates/user/edit/mail/index.html
  src/main/resources/templates/user/edit/password/index.html
Labels: fix

#271 CreatePlaceFormとCreateGooglePlaceFormを合体
  src/main/java/com/tabisketch/bean/form/CreateGooglePlaceForm.java
  src/main/java/com/tabisketch/bean/form/CreatePlaceForm.java
  src/main/java/com/tabisketch/controller/CreateGooglePlaceAPIController.java
  src/main/java/com/tabisketch/mapper/IGooglePlaceMapper.java
  src/main/java/com/tabisketch/service/ICreateGooglePlaceService.java
  src/main/java/com/tabisketch/service/implement/CreateGooglePlaceService.java
  src/main/java/com/tabisketch/service/implement/CreatePlaceService.java
  src/test/java/com/tabisketch/controller/CreateGooglePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/controller/CreatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/mapper/GooglePlaceMapperTest.java
  src/test/java/com/tabisketch/service/CreateGooglePlaceServiceTest.java
  src/test/java/com/tabisketch/service/CreatePlaceServiceTest.java
  src/test/resources/sql/CreateGooglePlace.sql
Labels: enhancement, java

#272 環境変数を.env (dotenv) にまとめた
  .env.example
  .github/workflows/build_and_run.yml
  .gitignore
  .run/BuildAndRun.run.xml
  .run/TailwindCSSBuild.run.xml
  .run/bin/BuildTailwindCss.sh
  .run/bin/CreateTables.sh
  .run/bin/DropTables.sh
  .run/sql/CreateTables.sql
  .run/sql/DropTables.sql
  README.md
  bin/BuildAndRun.sh
  bin/BuildJar.sh
  bin/BuildJarWithoutTest.sh
  bin/BuildTailwindCss.sh
  bin/CreateTables.sh
  bin/DropTables.sh
  sql/CreateTables.sql
  sql/DropTables.sql
  sql/create/CreateDaysTable.sql
  sql/create/CreateGooglePlaceTypesTable.sql
  sql/create/CreateGooglePlacesTable.sql
  sql/create/CreateGoogleTypeAssociationsTable.sql
  sql/create/CreateMAATokensTable.sql
  sql/create/CreatePackingsTable.sql
  sql/create/CreatePasswordResetTokensTable.sql
  sql/create/CreatePlacesTable.sql
  sql/create/CreatePlansTable.sql
  sql/create/CreateTransportationsType.sql
  sql/create/CreateUsersTable.sql
  sql/drop/DropDaysTable.sql
  sql/drop/DropGooglePlaceTypesTable.sql
  sql/drop/DropGooglePlacesTable.sql
  sql/drop/DropGoogleTypeAssociationsTable.sql
  sql/drop/DropMAATokensTable.sql
  sql/drop/DropPackingsTable.sql
  sql/drop/DropPasswordResetTokensTable.sql
  sql/drop/DropPlacesTable.sql
  sql/drop/DropPlansTable.sql
  sql/drop/DropTransportationsTable.sql
  sql/drop/DropUsersTable.sql
  src/main/resources/application.properties
Labels: refactor

#277 目的地編集APIを作成
  src/main/java/com/tabisketch/bean/form/UpdatePlaceForm.java
  src/main/java/com/tabisketch/bean/response/CreateGooglePlaceResponse.java
  src/main/java/com/tabisketch/bean/response/CreatePlaceResponse.java
  src/main/java/com/tabisketch/bean/response/CreatePlanResponse.java
  src/main/java/com/tabisketch/bean/response/UpdatePlaceResponse.java
  src/main/java/com/tabisketch/controller/UpdatePlaceAPIController.java
  src/main/java/com/tabisketch/mapper/IPlacesMapper.java
  src/main/java/com/tabisketch/service/IUpdatePlaceService.java
  src/main/java/com/tabisketch/service/implement/UpdatePlaceService.java
  src/test/java/com/tabisketch/controller/UpdatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/mapper/PlacesMapperTest.java
  src/test/java/com/tabisketch/service/UpdatePlaceServiceTest.java
Labels: enhancement, java

#281 Dockerのpostgresql起動構成を作成
  .env.example
  .github/workflows/build_and_run.yml
  README.md
  bin/CreateTables.sh
  bin/DropTables.sh
  docker/docker-compose.yml
  docker/postgresql/sql/01-create-users-table.sql
  docker/postgresql/sql/02-create-password-reset-tokens-table.sql
  docker/postgresql/sql/03-create-maa-tokens-table.sql
  docker/postgresql/sql/04-create-plans-table.sql
  docker/postgresql/sql/05-create-days-table.sql
  docker/postgresql/sql/06-create-google-places-table.sql
  docker/postgresql/sql/07-create-google-place-types-table.sql
  docker/postgresql/sql/08-create-google-type-associations-table.sql
  docker/postgresql/sql/09-create-transportations-type.sql
  docker/postgresql/sql/10-create-places-table.sql
  docker/postgresql/sql/11-create-packings-table.sql
  sql/CreateTables.sql
  sql/DropTables.sql
  sql/drop/DropDaysTable.sql
  sql/drop/DropGooglePlaceTypesTable.sql
  sql/drop/DropGooglePlacesTable.sql
  sql/drop/DropGoogleTypeAssociationsTable.sql
  sql/drop/DropMAATokensTable.sql
  sql/drop/DropPackingsTable.sql
  sql/drop/DropPasswordResetTokensTable.sql
  sql/drop/DropPlacesTable.sql
  sql/drop/DropPlansTable.sql
  sql/drop/DropTransportationsTable.sql
  sql/drop/DropUsersTable.sql
  src/main/resources/application.properties
Labels: enhancement, refactor

#284 password_reset_tokensテーブルのtokenの型をUUIDに変更
  docker/postgresql/sql/02-create-password-reset-tokens-table.sql
Labels: fix

#283 Placeを作成・更新した際、idをリターンするようにした
  src/main/java/com/tabisketch/bean/form/CreatePlaceForm.java
  src/main/java/com/tabisketch/bean/form/UpdatePlaceForm.java
  src/main/java/com/tabisketch/bean/response/CreatePlaceResponse.java
  src/main/java/com/tabisketch/bean/response/UpdatePlaceResponse.java
  src/main/java/com/tabisketch/controller/CreatePlaceAPIController.java
  src/main/java/com/tabisketch/controller/UpdatePlaceAPIController.java
  src/main/java/com/tabisketch/service/ICreatePlaceService.java
  src/main/java/com/tabisketch/service/IUpdatePlaceService.java
  src/main/java/com/tabisketch/service/implement/CreatePlaceService.java
  src/main/java/com/tabisketch/service/implement/UpdatePlaceService.java
  src/test/java/com/tabisketch/bean/entity/ExampleGooglePlace.java
  src/test/java/com/tabisketch/bean/entity/ExamplePlace.java
  src/test/java/com/tabisketch/bean/form/ExampleCreatePlaceForm.java
  src/test/java/com/tabisketch/bean/form/ExampleUpdatePlaceForm.java
  src/test/java/com/tabisketch/controller/CreatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/controller/UpdatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/service/CreatePlaceServiceTest.java
  src/test/java/com/tabisketch/service/UpdatePlaceServiceTest.java
Labels: enhancement

#287 npmライブラリのバージョンを固定
  package-lock.json
  package.json
Labels: refactor

#288 codeownersファイルを追加
  .github/CODEOWNERS
Labels: documentation

#298 dockerの起動・停止をnpmスクリプトに設定
  README.md
  package.json
Labels: enhancement

#296 改行コードがlfになるように設定
  .editorconfig
  .gitattributes
  .github/CODEOWNERS
  src/main/java/com/tabisketch/bean/form/CreateDayForm.java
  src/main/java/com/tabisketch/bean/form/CreatePlanForm.java
  src/main/java/com/tabisketch/bean/form/RegisterForm.java
  src/main/java/com/tabisketch/service/implement/CreateDayService.java
  src/main/java/com/tabisketch/service/implement/CreatePlanService.java
  src/main/java/com/tabisketch/service/implement/RegisterService.java
  src/test/java/com/tabisketch/bean/entity/ExampleDay.java
  src/test/java/com/tabisketch/bean/entity/ExampleMAAToken.java
  src/test/java/com/tabisketch/bean/entity/ExamplePlan.java
  src/test/java/com/tabisketch/bean/entity/ExampleUser.java
  src/test/java/com/tabisketch/bean/form/ExampleCreateDayForm.java
  src/test/java/com/tabisketch/bean/form/ExampleCreatePlanForm.java
  src/test/java/com/tabisketch/bean/form/ExampleEditMailAddressForm.java
  src/test/java/com/tabisketch/bean/form/ExampleEditPasswordForm.java
  src/test/java/com/tabisketch/bean/form/ExampleRegisterForm.java
  src/test/java/com/tabisketch/controller/AuthMailAddressControllerTest.java
  src/test/java/com/tabisketch/controller/CreateDayAPIControllerTest.java
  src/test/java/com/tabisketch/controller/CreatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/controller/CreatePlanAPIControllerTest.java
  src/test/java/com/tabisketch/controller/DeletePlanControllerTest.java
  src/test/java/com/tabisketch/controller/EditMailAddressControllerTest.java
  src/test/java/com/tabisketch/controller/EditPasswordControllerTest.java
  src/test/java/com/tabisketch/controller/EditPlanControllerTest.java
  src/test/java/com/tabisketch/controller/EditUserControllerTest.java
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
  src/test/java/com/tabisketch/controller/UpdatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/mapper/DaysMapperTest.java
  src/test/java/com/tabisketch/mapper/GooglePlaceMapperTest.java
  src/test/java/com/tabisketch/mapper/MAATokensMapperTest.java
  src/test/java/com/tabisketch/mapper/PlacesMapperTest.java
  src/test/java/com/tabisketch/mapper/PlansMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/service/AuthMailAddressServiceTest.java
  src/test/java/com/tabisketch/service/CreateDayServiceTest.java
  src/test/java/com/tabisketch/service/CreatePlanServiceTest.java
  src/test/java/com/tabisketch/service/DeletePlanServiceTest.java
  src/test/java/com/tabisketch/service/EditMailAddressServiceTest.java
  src/test/java/com/tabisketch/service/EditPasswordServiceTest.java
  src/test/java/com/tabisketch/service/EncryptPasswordServiceTest.java
  src/test/java/com/tabisketch/service/ListPlanServiceTest.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
  src/test/java/com/tabisketch/service/SendMailServiceTest.java
  src/test/resources/sql/CreateGooglePlace.sql
Labels: refactor

#299 apiパッケージを作成
  src/main/java/com/tabisketch/api/CreateDayAPIController.java
  src/main/java/com/tabisketch/api/CreatePlaceAPIController.java
  src/main/java/com/tabisketch/api/CreatePlanAPIController.java
  src/main/java/com/tabisketch/api/UpdatePlaceAPIController.java
  src/test/java/com/tabisketch/api/CreateDayAPIControllerTest.java
  src/test/java/com/tabisketch/api/CreatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/api/CreatePlanAPIControllerTest.java
  src/test/java/com/tabisketch/api/UpdatePlaceAPIControllerTest.java
Labels: refactor, java

#302 CSRF対策の行追加
  src/main/resources/templates/fragment/head.html
Labels: fix

#297 パスワードリセット機能を作成
  src/main/java/com/tabisketch/bean/entity/PasswordResetToken.java
  src/main/java/com/tabisketch/bean/form/ResetPasswordForm.java
  src/main/java/com/tabisketch/bean/form/SendResetPasswordForm.java
  src/main/java/com/tabisketch/controller/ResetPasswordController.java
  src/main/java/com/tabisketch/controller/SendResetPasswordController.java
  src/main/java/com/tabisketch/exception/SelectFailedException.java
  src/main/java/com/tabisketch/mapper/IPasswordResetTokensMapper.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/main/java/com/tabisketch/service/IResetPasswordService.java
  src/main/java/com/tabisketch/service/ISendResetPasswordService.java
  src/main/java/com/tabisketch/service/implement/ResetPasswordService.java
  src/main/java/com/tabisketch/service/implement/SendResetPasswordService.java
  src/main/java/com/tabisketch/valueobject/Mail.java
  src/main/resources/templates/login.html
  src/main/resources/templates/password-reset/index.html
  src/main/resources/templates/password-reset/reset.html
  src/main/resources/templates/password-reset/send.html
  src/main/resources/templates/user/password-reset/send.html
  src/test/java/com/tabisketch/bean/entity/ExamplePasswordResetToken.java
  src/test/java/com/tabisketch/bean/form/ExampleResetPasswordForm.java
  src/test/java/com/tabisketch/bean/form/ExampleSendResetPasswordForm.java
  src/test/java/com/tabisketch/controller/ResetPasswordControllerTest.java
  src/test/java/com/tabisketch/controller/SendResetPasswordControllerTest.java
  src/test/java/com/tabisketch/mapper/PasswordResetTokensMapperTest.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/service/ResetPasswordServiceTest.java
  src/test/java/com/tabisketch/service/SendResetPasswordServiceTest.java
  src/test/resources/sql/CreatePasswordResetToken.sql
Labels: enhancement, WIP

#303 README Docker 破棄コマンド部分の説明を変更
  README.md
Labels: documentation

#316 Revert "Merge pull request #300 from saitokazumasa3/dependabot/npm_an…
  package-lock.json
  package.json
Labels: tailwind, fix

#311 Docker jarビルドファイルを更新
  docker/app/Dockerfile
  pom.xml
Labels: refactor

#308 ビルドとデプロイに使用するファイルを作成
  bin/BuildAndRun.sh
  bin/BuildJarWithoutTest.sh
  bin/BuildTailwindCss.sh
  cloudbuild.yaml
  docker/app/Dockerfile
  docker/docker-compose.yml
  docker/postgresql/Dockerfile
  package.json
  pom.xml
Labels: enhancement

#313 ログインするとエラーが発生するバグを修正
  src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
Labels: bug, java

#319 AuthMailAddressServiceの実装し足りない部分を実装
  src/main/java/com/tabisketch/controller/AuthMailAddressController.java
  src/main/java/com/tabisketch/mapper/IUsersMapper.java
  src/main/java/com/tabisketch/service/IAuthMailAddressService.java
  src/main/java/com/tabisketch/service/implement/AuthMailAddressService.java
  src/test/java/com/tabisketch/mapper/UsersMapperTest.java
  src/test/java/com/tabisketch/service/AuthMailAddressServiceTest.java
Labels: refactor, java

#321 CreatePlaceServiceにコメント追記
  src/main/java/com/tabisketch/service/implement/CreatePlaceService.java
Labels: refactor, java

#320 CreateDayService&SendMailServiceのコメント追記、実装し足りない部分を実装
  src/main/java/com/tabisketch/service/implement/CreateDayService.java
  src/main/java/com/tabisketch/service/implement/SendMailService.java
  src/test/java/com/tabisketch/service/CreateDayServiceTest.java
  src/test/java/com/tabisketch/service/SendMailServiceTest.java
Labels: refactor, java

#323 CreatePlanServiceの実装し足りない部分を実装
  src/main/java/com/tabisketch/api/CreatePlanAPIController.java
  src/main/java/com/tabisketch/service/ICreatePlanService.java
  src/main/java/com/tabisketch/service/implement/CreatePlanService.java
  src/test/java/com/tabisketch/service/CreatePlanServiceTest.java
Labels: refactor, java

#326 デプロイの際に環境変数が正しく設定されない不具合の修正
  cloudbuild.yaml
Labels: fix

#325 DeletePlanServiceにコメント追記
  src/main/java/com/tabisketch/service/implement/DeletePlanService.java
  src/test/java/com/tabisketch/service/DeletePlanServiceTest.java
Labels: refactor, java

#327 EditMailAddressServiceを見やすいようにリファクタ
  src/main/java/com/tabisketch/bean/form/EditMailAddressForm.java
  src/main/java/com/tabisketch/controller/EditMailAddressController.java
  src/main/java/com/tabisketch/service/IEditMailAddressService.java
  src/main/java/com/tabisketch/service/implement/EditMailAddressService.java
  src/test/java/com/tabisketch/service/EditMailAddressServiceTest.java
Labels: refactor, java

#310 Map上に経路を表示する機能の作成
  src/main/resources/static/js/map.js
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/plan/edit.html
Labels: WIP

#328 EditPasswordServiceを見やすいようにリファクタ
  src/main/java/com/tabisketch/controller/EditPasswordController.java
  src/main/java/com/tabisketch/service/IEditPasswordService.java
  src/main/java/com/tabisketch/service/implement/EditPasswordService.java
  src/main/java/com/tabisketch/service/implement/ResetPasswordService.java
  src/test/java/com/tabisketch/service/EditPasswordServiceTest.java
Labels: refactor, java

#329 RegisterServiceに実装し足りない部分を実装
  src/main/java/com/tabisketch/controller/RegisterController.java
  src/main/java/com/tabisketch/service/IRegisterService.java
  src/main/java/com/tabisketch/service/implement/RegisterService.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
Labels: refactor, java

#331 マップの描画方法を修正
  src/main/resources/static/js/map.js
Labels: refactor

#334 Dockerでjavaのテストを実行するdocker serviceを作成
  README.md
  docker/docker-compose.test.yml
  docker/docker-compose.yml
  docker/test/Dockerfile
  package.json
Labels: enhancement, java

#332 Exception記載方法を変更
  src/main/java/com/tabisketch/api/CreateDayAPIController.java
  src/main/java/com/tabisketch/api/CreatePlaceAPIController.java
  src/main/java/com/tabisketch/api/CreatePlanAPIController.java
  src/main/java/com/tabisketch/api/UpdatePlaceAPIController.java
  src/main/java/com/tabisketch/bean/response/implement/CreateDayResponse.java
  src/main/java/com/tabisketch/bean/response/implement/CreatePlaceResponse.java
  src/main/java/com/tabisketch/bean/response/implement/CreatePlanResponse.java
  src/main/java/com/tabisketch/bean/response/implement/UpdatePlaceResponse.java
  src/main/java/com/tabisketch/controller/EditMailAddressController.java
  src/main/java/com/tabisketch/controller/EditPasswordController.java
  src/main/java/com/tabisketch/controller/RegisterController.java
  src/main/java/com/tabisketch/exception/InsertFailedException.java
  src/main/java/com/tabisketch/exception/InvalidMailAddressException.java
  src/main/java/com/tabisketch/exception/InvalidPasswordException.java
  src/main/java/com/tabisketch/exception/SelectFailedException.java
  src/main/java/com/tabisketch/exception/UpdateFailedException.java
  src/main/java/com/tabisketch/service/IEditMailAddressService.java
  src/main/java/com/tabisketch/service/IEditPasswordService.java
  src/main/java/com/tabisketch/service/IRegisterService.java
  src/main/java/com/tabisketch/service/implement/AuthMailAddressService.java
  src/main/java/com/tabisketch/service/implement/CreateDayService.java
  src/main/java/com/tabisketch/service/implement/CreatePlaceService.java
  src/main/java/com/tabisketch/service/implement/CreatePlanService.java
  src/main/java/com/tabisketch/service/implement/DeletePlanService.java
  src/main/java/com/tabisketch/service/implement/EditMailAddressService.java
  src/main/java/com/tabisketch/service/implement/EditPasswordService.java
  src/main/java/com/tabisketch/service/implement/RegisterService.java
  src/main/java/com/tabisketch/service/implement/ResetPasswordService.java
  src/main/java/com/tabisketch/service/implement/SendResetPasswordService.java
  src/main/java/com/tabisketch/service/implement/UpdatePlaceService.java
  src/test/java/com/tabisketch/api/CreateDayAPIControllerTest.java
  src/test/java/com/tabisketch/api/CreatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/api/CreatePlanAPIControllerTest.java
  src/test/java/com/tabisketch/api/UpdatePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/service/EditMailAddressServiceTest.java
  src/test/java/com/tabisketch/service/EditPasswordServiceTest.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
Labels: refactor, java

#336 プラン編集画面作成（発表用）
  src/main/java/com/tabisketch/controller/EditPlanController.java
  src/main/resources/static/js/map.js
  src/main/resources/templates/plan/edit.html
  src/main/resources/templates/plan/present-edit.html
Labels: enhancement

#335 GithubActions メインテストの改善
  .github/workflows/bin/init_db.sh
  .github/workflows/build_and_run.yml
  bin/BuildJar.sh
  docker/01-docker-compose.yml
  docker/02-docker-compose.test.yml
  docker/bin/docker_compose_build.sh
  docker/bin/docker_compose_down.sh
  docker/bin/docker_compose_test.sh
  docker/bin/docker_compose_up.sh
  package.json
Labels: refactor

#343 プレゼン用の表示修正
  src/main/resources/templates/plan/create.html
  src/main/resources/templates/plan/edit.html
Labels: fix

#346 plan/listページのfragment読み込み記法を最新のものに変更
  src/main/resources/templates/plan/list.html
Labels: fix

#348 Placeの削除APIを作成
  src/main/java/com/tabisketch/api/DeletePlaceAPIController.java
  src/main/java/com/tabisketch/bean/form/DeletePlaceForm.java
  src/main/java/com/tabisketch/bean/response/implement/DeletePlaceResponse.java
  src/main/java/com/tabisketch/controller/DeletePlanController.java
  src/main/java/com/tabisketch/mapper/IPlacesMapper.java
  src/main/java/com/tabisketch/service/IDeletePlaceService.java
  src/main/java/com/tabisketch/service/implement/DeletePlaceService.java
  src/test/java/com/tabisketch/api/DeletePlaceAPIControllerTest.java
  src/test/java/com/tabisketch/bean/form/ExampleDeletePlaceForm.java
  src/test/java/com/tabisketch/mapper/PlacesMapperTest.java
  src/test/java/com/tabisketch/service/DeletePlaceServiceTest.java
Labels: enhancement, java

#350 Dayの削除APIを作成
  src/main/java/com/tabisketch/api/DeleteDayAPIControler.java
  src/main/java/com/tabisketch/mapper/IDaysMapper.java
  src/main/java/com/tabisketch/service/IDeleteDayService.java
  src/main/java/com/tabisketch/service/implement/DeleteDayService.java
  src/test/java/com/tabisketch/api/DeleteDayAPIControllerTest.java
  src/test/java/com/tabisketch/mapper/DaysMapperTest.java
  src/test/java/com/tabisketch/service/DeleteDayServiceTest.java
Labels: enhancement, java
