Repository saitokazumasa/tabisketch, pull requests merged in 2025-02, with the labels that each got.

#258 modalフラグメントの修正 placesの登録作成
  src/main/resources/static/js/autocomplete.js
  src/main/resources/static/js/modal.js
  src/main/resources/templates/fragment/modal.html
  src/main/resources/templates/fragment/update-modal.html
Labels: fix, javascript

#358 トップ画面の修正
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/top.html
Labels: fix, HTML

#366 ローディング表示の作成
  src/main/resources/templates/fragment/svg.html
Labels: enhancement, tailwind, HTML

#262 おすすめ目的地表示のフラグメント修正
  src/main/resources/static/js/recommend.js
  src/main/resources/templates/fragment/recommend.html
Labels: fix, HTML

#371 [refactor] 公共交通機関のコードを削除
  src/main/resources/static/js/map.js
Labels: refactor

#378 LocalTime整形用DateTimeFormatの追加
  src/main/java/com/tabisketch/bean/form/CreatePlaceForm.java
  src/main/java/com/tabisketch/bean/form/UpdatePlaceForm.java
Labels: refactor

#384 目的地削除のイベント追加
  src/main/resources/static/js/modalElement.js
Labels: enhancement

#374 持ち物リストページの作成
  src/main/resources/static/js/packings.js
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/share/packings.html
Labels: enhancement, tailwind, javascript, HTML

#381 modal.jsの修正・更新と削除機能追加
  src/main/resources/static/js/errorMessage.js
  src/main/resources/static/js/formValidate.js
  src/main/resources/static/js/modal.js
  src/main/resources/static/js/modalElement.js
  src/main/resources/static/js/modalForm.js
  src/main/resources/static/js/recommend.js
  src/main/resources/templates/fragment/modal.html
  src/main/resources/templates/fragment/recommend.html
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/fragment/update-modal.html
Labels: enhancement, fix, javascript, HTML

#401 docker-composeを読み込むbinコマンドを改善
  docker/bin/docker_compose_build.sh
  docker/bin/docker_compose_down.sh
  docker/bin/docker_compose_test.sh
  docker/bin/docker_compose_up.sh
Labels: refactor

#402 dependabotを削除
  .github/dependabot.yml
Labels: refactor

#408 eslintのactionsを削除
  .github/workflows/eslint.yml
Labels: refactor

#405 outputをviewModelに変更
  src/main/java/com/tabisketch/bean/output/PlanOutput.java
  src/main/java/com/tabisketch/bean/view_model/PlanViewModel.java
  src/main/java/com/tabisketch/controller/ListPlansController.java
  src/main/java/com/tabisketch/rest_controller/EditPlanRestController.java
  src/main/java/com/tabisketch/service/IEditPlanService.java
  src/main/java/com/tabisketch/service/IListPlanService.java
  src/main/java/com/tabisketch/service/implement/EditPlanService.java
  src/main/java/com/tabisketch/service/implement/ListPlanService.java
  src/test/java/com/tabisketch/bean/view_model/ExamplePlanViewModel.java
  src/test/java/com/tabisketch/rest_controller/EditPlanRestControllerTest.java
Labels: refactor

#406 PRテンプレを更新
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#407 PR自動アサインactionを追加
  .github/workflows/auto_assign.yml
Labels: refactor

#409 build_and_run.ymlのenvを更新
  .github/workflows/build_and_run.yml
Labels: refactor

#403 init_db.shをリファクタ
  .github/workflows/bin/init_db.sh
  .github/workflows/build_and_run.yml
  docker/bin/docker_compose_build.sh
  docker/bin/docker_compose_down.sh
  docker/bin/docker_compose_test.sh
  docker/bin/docker_compose_up.sh
  docker/bin/init_db.sh
Labels: refactor

#411 シークレット名を修正
  cloudbuild.yaml
Labels: fix

#404 ポップアップされる時のマップ描画処理追加
  src/main/resources/static/js/map.js
  src/main/resources/templates/fragment/script.html
Labels: javascript

#413 メール認証URLのリファクタ
  .github/workflows/auto_assign.yml
  src/main/java/com/tabisketch/bean/form/SendMailForm.java
  src/main/java/com/tabisketch/configuration/WebSecurityConfiguration.java
  src/main/java/com/tabisketch/controller/EditUserController.java
  src/main/java/com/tabisketch/controller/RegisterController.java
  src/main/java/com/tabisketch/controller/VerifyEmailController.java
  src/main/java/com/tabisketch/service/implement/EditEmailService.java
  src/main/java/com/tabisketch/service/implement/EditPasswordService.java
  src/main/java/com/tabisketch/service/implement/SendEditEmailMailService.java
  src/main/java/com/tabisketch/service/implement/SendMailService.java
  src/main/resources/templates/mail/complate.html
  src/main/resources/templates/user/edit/email/complate.html
  src/main/resources/templates/user/edit/index.html
  src/test/java/com/tabisketch/controller/EditUserControllerTest.java
  src/test/java/com/tabisketch/controller/RegisterControllerTest.java
  src/test/java/com/tabisketch/controller/VerifyEmailControllerTest.java
  src/test/java/com/tabisketch/service/EditPasswordServiceTest.java
  src/test/java/com/tabisketch/service/SendEdtiEmailMailServiceTest.java
Labels: refactor

#415 プランの所有者以外でも削除・編集できてしまうのを修正
  src/main/java/com/tabisketch/rest_controller/DeletePlanRestController.java
  src/main/java/com/tabisketch/rest_controller/EditPlanRestController.java
  src/main/java/com/tabisketch/service/IDeletePlanService.java
  src/main/java/com/tabisketch/service/IEditPlanService.java
  src/main/java/com/tabisketch/service/implement/DeletePlanService.java
  src/main/java/com/tabisketch/service/implement/EditPlanService.java
  src/test/java/com/tabisketch/rest_controller/EditPlanRestControllerTest.java
  src/test/java/com/tabisketch/service/DeletePlanServiceTest.java
  src/test/java/com/tabisketch/service/EditPlanServiceTest.java
Labels: bug, refactor

#416 一部URLを変更
  src/main/java/com/tabisketch/controller/CreatePlanController.java
  src/main/java/com/tabisketch/controller/EditPlanController.java
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
  src/test/java/com/tabisketch/controller/EditPlanControllerTest.java
Labels: refactor

#420 サービスのテストの書き方を間違っていたため修正
  src/test/java/com/tabisketch/bean/entity/ExampleEmailVerificationToken.java
  src/test/java/com/tabisketch/bean/entity/ExampleNewEmailVerificartionToken.java
  src/test/java/com/tabisketch/bean/entity/ExampleResetPasswordToken.java
  src/test/java/com/tabisketch/service/CreatePlanServiceTest.java
  src/test/java/com/tabisketch/service/DeletePlanServiceTest.java
  src/test/java/com/tabisketch/service/EditEmailServiceTest.java
  src/test/java/com/tabisketch/service/EditPasswordServiceTest.java
  src/test/java/com/tabisketch/service/EditPlanServiceTest.java
  src/test/java/com/tabisketch/service/FindOnePlanWithUserServiceTest.java
  src/test/java/com/tabisketch/service/ListPlanServiceTest.java
  src/test/java/com/tabisketch/service/RegisterServiceTest.java
  src/test/java/com/tabisketch/service/ResetPasswordServiceTest.java
  src/test/java/com/tabisketch/service/SendEdtiEmailMailServiceTest.java
  src/test/java/com/tabisketch/service/SendMailServiceTest.java
  src/test/java/com/tabisketch/service/SendResetPasswordMailServiceTest.java
  src/test/java/com/tabisketch/service/VerifyEmailServiceTest.java
Labels: bug, fix

#424 スマホ画面のメニュー表示修正
  src/main/resources/static/js/header.js
  src/main/resources/templates/fragment/header.html
Labels: fix

#426 プラン一覧画面の修正
  src/main/resources/templates/plan/list.html
Labels: fix

#418 完了画面のスタイル作成と、ファイル名修正
  src/main/java/com/tabisketch/controller/EditUserController.java
  src/main/java/com/tabisketch/controller/ResetPasswordController.java
  src/main/java/com/tabisketch/controller/VerifyEmailController.java
  src/main/resources/templates/mail/complate.html
  src/main/resources/templates/mail/complete.html
  src/main/resources/templates/reset-password/complate.html
  src/main/resources/templates/reset-password/complete.html
  src/main/resources/templates/user/edit/password/complete.html
  src/test/java/com/tabisketch/controller/EditUserControllerTest.java
  src/test/java/com/tabisketch/controller/ResetPasswordControllerTest.java
  src/test/java/com/tabisketch/controller/VerifyEmailControllerTest.java
Labels: tailwind, fix, refactor

#428 テーブルをfix
  docker/postgresql/sql/08-create-departure-points-table.sql
  docker/postgresql/sql/08-create-start-places-table.sql
  docker/postgresql/sql/09-create-destinations-table.sql
  docker/postgresql/sql/09-create-waypoints-table.sql
  docker/postgresql/sql/10-create-destination-points-table.sql
  docker/postgresql/sql/10-create-route-infos-table.sql
  src/main/java/com/tabisketch/bean/entity/DeparturePoint.java
  src/main/java/com/tabisketch/bean/entity/DestinationPoint.java
  src/main/java/com/tabisketch/bean/entity/Waypoint.java
Labels: fix

#429 持ち物テーブルをfix
  docker/postgresql/sql/11-create-belongings-table.sql
  src/main/java/com/tabisketch/bean/entity/Belonging.java
Labels: fix

#430 各種テーブルをfix
  docker/postgresql/sql/08-create-departure-points-table.sql
  docker/postgresql/sql/09-create-waypoints-table.sql
  docker/postgresql/sql/10-create-destination-points-table.sql
  src/main/java/com/tabisketch/bean/entity/Belonging.java
  src/main/java/com/tabisketch/bean/entity/DeparturePoint.java
  src/main/java/com/tabisketch/bean/entity/DestinationPoint.java
  src/main/java/com/tabisketch/bean/entity/Waypoint.java
Labels: fix

#433 Update→Editに統一
  src/main/java/com/tabisketch/bean/form/EditDeparturePointForm.java
  src/main/java/com/tabisketch/bean/form/EditDestinationPointForm.java
  src/main/java/com/tabisketch/bean/form/EditWaypointForm.java
  src/main/java/com/tabisketch/bean/form/EditWaypointListForm.java
  src/main/java/com/tabisketch/bean/form/UpdateWaypointListForm.java
  src/test/java/com/tabisketch/bean/form/ExampleEditWaypointListForm.java
Labels: refactor

#434 plan/createをした時にリダイレクトせず、createページに遷移するようにした
  src/main/java/com/tabisketch/controller/CreatePlanController.java
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
Labels: fix

#412 プラン作成ページ作成（/plan/create/{uuid}）
  src/main/resources/static/js/autocomplete.js
  src/main/resources/static/js/check.js
  src/main/resources/static/js/editButtons.js
  src/main/resources/static/js/editForm.js
  src/main/resources/static/js/errorMessage.js
  src/main/resources/static/js/formValidate.js
  src/main/resources/static/js/modal.js
  src/main/resources/static/js/modalElement.js
  src/main/resources/static/js/modalForm.js
  src/main/resources/static/js/svgCheckbox.js
  src/main/resources/static/js/svgThreeRadio.js
  src/main/resources/templates/fragment/modal.html
  src/main/resources/templates/fragment/popup.html
  src/main/resources/templates/fragment/recommend.html
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/fragment/svg.html
  src/main/resources/templates/fragment/update-modal.html
  src/main/resources/templates/plan/create.html
  src/main/resources/templates/plan/edit.html
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
  src/test/java/com/tabisketch/controller/EditPlanControllerTest.java
Labels: javascript, HTML

#435 【WIP】APIを廃止、通常のControllerに機能を移した
  src/main/java/com/tabisketch/bean/view_model/PlanViewModel.java
  src/main/java/com/tabisketch/bean/view_model/WaypointListViewModel.java
  src/main/java/com/tabisketch/controller/CreatePlanController.java
  src/main/java/com/tabisketch/controller/DeletePlanController.java
  src/main/java/com/tabisketch/controller/EditPlanController.java
  src/main/java/com/tabisketch/controller/ListPlansController.java
  src/main/java/com/tabisketch/rest_controller/EditPlanRestController.java
  src/main/java/com/tabisketch/service/ICreatePlanService.java
  src/main/java/com/tabisketch/service/ICreateWaypointListService.java
  src/main/java/com/tabisketch/service/IEditPlanService.java
  src/main/java/com/tabisketch/service/IEditWaypointListService.java
  src/main/java/com/tabisketch/service/IListPlanService.java
  src/main/java/com/tabisketch/service/implement/CreatePlanService.java
  src/main/java/com/tabisketch/service/implement/CreateWaypointListService.java
  src/main/java/com/tabisketch/service/implement/EditPlanService.java
  src/main/java/com/tabisketch/service/implement/EditWaypointListService.java
  src/main/java/com/tabisketch/service/implement/ListPlanService.java
  src/test/java/com/tabisketch/bean/form/ExampleCreateDeparturePointForm.java
  src/test/java/com/tabisketch/bean/form/ExampleCreateDestinationPointForm.java
  src/test/java/com/tabisketch/bean/form/ExampleCreateWaypointForm.java
  src/test/java/com/tabisketch/bean/form/ExampleCreateWaypointListForm.java
  src/test/java/com/tabisketch/bean/view_model/ExamplePlanViewModel.java
  src/test/java/com/tabisketch/bean/view_model/ExampleWaypointListViewModel.java
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
  src/test/java/com/tabisketch/controller/DeletePlanControllerTest.java
  src/test/java/com/tabisketch/controller/EditPlanControllerTest.java
  src/test/java/com/tabisketch/rest_controller/EditPlanRestControllerTest.java
  src/test/java/com/tabisketch/service/CreatePlanServiceTest.java
  src/test/java/com/tabisketch/service/EditPlanServiceTest.java
Labels: enhancement

#436 CreatePlanServiceのリターン値を変更
  src/main/java/com/tabisketch/bean/form/EditPlanForm.java
  src/main/java/com/tabisketch/controller/CreatePlanController.java
  src/main/java/com/tabisketch/service/ICreatePlanService.java
  src/main/java/com/tabisketch/service/implement/CreatePlanService.java
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
Labels: enhancement

#438 編集画面の表示のみ作成（plan/edit）
  src/main/resources/templates/fragment/script.html
  src/main/resources/templates/fragment/update-modal.html
  src/main/resources/templates/plan/edit.html
Labels: HTML

#437 経路生成ボタンを押したときにDBに保存される機能を実装
  src/main/java/com/tabisketch/bean/entity/DestinationPoint.java
  src/main/java/com/tabisketch/bean/form/CreateDeparturePointForm.java
  src/main/java/com/tabisketch/bean/form/CreateDestinationPointForm.java
  src/main/java/com/tabisketch/bean/form/CreateWaypointForm.java
  src/main/java/com/tabisketch/bean/form/CreateWaypointListForm.java
  src/main/java/com/tabisketch/bean/form/EditDeparturePointForm.java
  src/main/java/com/tabisketch/bean/form/EditDestinationPointForm.java
  src/main/java/com/tabisketch/bean/form/EditWaypointForm.java
  src/main/java/com/tabisketch/bean/form/EditWaypointListForm.java
  src/main/java/com/tabisketch/controller/CreatePlanController.java
  src/main/java/com/tabisketch/mapper/IDeparturePointsMapper.java
  src/main/java/com/tabisketch/mapper/IDestinationPointsMapper.java
  src/main/java/com/tabisketch/mapper/IWaypointsMapper.java
  src/main/java/com/tabisketch/rest_controller/CreateWaypointListRestController.java
  src/main/java/com/tabisketch/service/ICreateWaypointListService.java
  src/main/java/com/tabisketch/service/implement/CreateWaypointListService.java
  src/test/java/com/tabisketch/bean/entity/ExampleDeparturePoint.java
  src/test/java/com/tabisketch/bean/entity/ExampleDestinationPoint.java
  src/test/java/com/tabisketch/bean/entity/ExampleWaypoint.java
  src/test/java/com/tabisketch/bean/form/ExampleCreateWaypointListForm.java
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
  src/test/java/com/tabisketch/mapper/DeparturePointsMapperTest.java
  src/test/java/com/tabisketch/mapper/DestinationPointsMapperTest.java
  src/test/java/com/tabisketch/mapper/WaypointsMapperTest.java
  src/test/java/com/tabisketch/rest_controller/CreateWaypointListRestControllerTest.java
  src/test/java/com/tabisketch/service/CreateWaypointListServiceTest.java
  src/test/resources/sql/InsertExampleDeparturePoint.sql
  src/test/resources/sql/InsertExampleDestinationPoint.sql
  src/test/resources/sql/InsertExampleWaypoint.sql
Labels: enhancement

#441 CreatePlanControllerをpostした時にプランも編集するようにした
  src/main/java/com/tabisketch/controller/CreatePlanController.java
  src/main/java/com/tabisketch/service/IEditPlanService.java
  src/main/java/com/tabisketch/service/implement/EditPlanService.java
  src/test/java/com/tabisketch/controller/CreatePlanControllerTest.java
Labels: enhancement
